sonar.organization=mirasen-io
sonar.projectKey=mirasen-io_chessboard
sonar.projectName=chessboard

sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage*/**/lcov.info

# sonar.exclusions=src/routes/**/*
sonar.cpd.exclusions=tests/**/*,e2e/**/*,src/**/*.spec.ts
